# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
 # - name: Home
 #   url: '#about'
 #   weight: 10
  - name: Ensino
    url: '#teach'
    weight: 10
  - name: Projetos
    url: '#projects'
    weight: 20
  - name: Apresentações
    url: '#talks'
    weight: 30
  - name: Publicações
    url: '#featured'
    weight: 40
  - name: Postagens
    url: '#posts'
    weight: 50
  - name: Contato
    url: '#contact'
    weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
